[package]
name = "gel-o"
version = "0.1.0"
authors = ["Max Blachman <blachmanmax@gmail.com>"]
edition = "2018"

[lib]
name = "libgelo"
path = "src/lib.rs"

[dependencies]
evdev-rs = "0.4.0"
epoll = "4.1.0"
inotify = "0.8.2"